### PR TITLE
Check latest local autosave against latest save (fixes #2259)

### LINKED ISSUE #2259: Notebook history does not hide "Unsaved Changes"
With the latest changes, expected behavior for notebook history is to hide "Unsaved Changes" when there are no differences. However, this does not hold in a case.

# Steps to Reproduce
1. Create a new notebook
2. In an empty line, press enter and delete
3. "Unsaved Changes" with "No difference." shows up
4. Page refresh fixes

### PR DESCRIPTION
**Pull request by mehmetoguzderin**
Fix for https://github.com/iodide-project/iodide/issues/2259

# Explanation
The current implementation shows unsaved changes whenever local autosave entry is created, which is never reduced back when there are no changes (e.g., create a new line and remove it immediately). This new implementation further checks the local autosave with the latest revision to ensure that there are no changes.

### CODE REVIEW

File: src/editor/actions/history-modal-actions.js [hunk 1]
```diff
@@ -70,13 +70,28 @@ export function getNotebookRevisionList() {
...
+        getLocalAutosave(getState())
+          .then(localAutosaveState => {
+            let hasLocalOnlyChanges = false;
+            if (
+              "revisionContent" in getState().notebookHistory &&
+              "iomd" in localAutosaveState
+            ) {
+              if (
+                revisionList[0].id in getState().notebookHistory.revisionContent
+              ) {
```
Comment (wlach) [inline src/editor/actions/history-modal-actions.js]: Looking at this again, we could just rewrite this in a single expression (I know the formatting is wrong):

```js
const hasLocalOnlyChanges = ("iomd" in localAutosaveState  && 
  "revisionContent" in getState().notebookHistory && 
  revisionList.length &&
  revisionList[0].id in getState().notebookHistory.revisionContent &&                   
  localAutosaveState.iomd !== getState().notebookHistory.revisionContent[revisionList[0].id]);
```

This also checks for the edge case where the revision list has a length of 0 (should never happen but who knows).

**Comment by wlach** [comment]
Thank you!
