### PR TITLE
Make closing console pane from the GUI work again (fixes #815)

### LINKED ISSUE #815: Closing Console/DV panes using cross button throws error
Closing Console/DV/App History pane by clicking the cross button does not work. The header gets changed to `PANE MODE UNDEFINED!!` while the pane is still there. Using keybindings such as `Ctrl+H` etc. works as expected.

### PR DESCRIPTION
**Pull request by wlach**

### CODE REVIEW

File: src/eval-frame/actions/eval-frame-tasks.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ tasks.closePanes = new UserTask({
   callback() {
     postActionToEditor({
       type: 'CHANGE_SIDE_PANE_MODE',
-      sidePaneMode: '_CLOSED',
+      mode: '_CLOSED',
```
Comment (bcolloran) [inline src/eval-frame/actions/eval-frame-tasks.js]: hmm, tbh, i think it would be better to change the "CHANGE_SIDE_PANE_MODE" reducer in `src/eval-frame/reducers/eval-frame-reducer.js` and `/src/reducers/notebook-reducer.js` to look for `action.sidePaneMode` rather than changing this to pass "mode" since "mode" is not very descriptive and is already used elsewhere to mean the global mode

Comment (wlach) [reply src/eval-frame/actions/eval-frame-tasks.js]: Makes sense, I was thinking that myself while working on this, but wasn't sure. I'll fix things up tomorrow.

**Comment by wlach** [comment]
@bcolloran Fixed it up the way you suggested, can you take another look?

**Comment by bcolloran** [comment]
looks great. fixed a merge conflict, we can merge as soon as CI completes
