### PR TITLE
if I am not logged in and I log in on a notebook I own, set user_can_save = true

### LINKED ISSUE #1440: incorrect "This notebook is owned by another user" message after login
when i visit a notebook owned by my user via URL in a non-logged in state, the yellow message header first correctly shows the "You can modify and experiment with this notebook freely. To save to this server, you need to login." message.

however, after logging in, i am incorrectly shown "This notebook is owned by another user. Make a copy to your account." This goes away on refresh, but it should never be displayed in the first place when you log in under the owning account

### PR DESCRIPTION
**Pull request by hamilton**
fixes #1440 - this will remove the bar that says "this notebook is owned by another user" when you log into a notebook you own.

### CODE REVIEW

File: src/reducers/notebook-reducer.js [hunk 1]
```diff
@@ -210,7 +209,11 @@ const notebookReducer = (state = newNotebook(), action) => {
 
     case "LOGIN_SUCCESS": {
       const { userData } = action;
-      return Object.assign({}, state, { userData });
+      const { notebookInfo } = state;
+      if (userData.name === state.notebookInfo.username) {
+        notebookInfo.user_can_save = true;
+      }
+      return Object.assign({}, state, { userData }, { notebookInfo });
```
Comment (wlach) [inline src/reducers/notebook-reducer.js]: I wonder if this could be written more concisely as:
```js
return Object.assign({}, state, { userData }, { notebookInfo: { ...state.notebookInfo, user_can_save: userData.name === state.notebookInfo.username });
```

**Comment by bcolloran** [comment]
lgtm!

**Comment by wlach** [comment]
Circle issues now sorted so feel free to land whenever. I'd suggest making the change I outline above, but I'm fine either way.

**Comment by wlach** [comment]
I modified the changelog message slightly for brevity and clarity

**Comment by hamilton** [comment]
np, thanks @wlach
