### PR TITLE
fixes the interstitial appearing with the /new url

### LINKED ISSUE #917: "create new notebook" button takes me to the /new URL, but I also get an interstitial saying "this notebook is owned by another user"
screen shot 2018-09-18 at 12 27 08 pm

### PR DESCRIPTION
**Pull request by hamilton**
Fixes #917. 

- created a new function in `handle-server-variables.js` which operates similarly to `handleInitialJsmd` - it helps initiate the store with non-store data, particularly using the `getNotebookInfo`
- updated the `new_notebook_view` to pass by default to `user_can_save: true` (since atm login is required to create a new notebook, we'll want to change this later)

### CODE REVIEW

File: src/reducers/notebook-reducer.js [hunk 1]
```diff
@@ -55,6 +55,9 @@ const notebookReducer = (state = newNotebook(), action) => {
     case 'TOGGLE_WRAP_IN_EDITORS':
       return Object.assign({}, state, { wrapEditors: !state.wrapEditors })
 
+    case 'UPDATE_NOTEBOOK_INFO':
```
Comment (mdboom) [inline src/reducers/notebook-reducer.js]: I think `IMPORT_NOTEBOOK` already handles the notebookInfo...  Would it be less redundant to just make sure `IMPORT_NOTEBOOK` is fired when making a new notebook, rather than adding a new action?

Comment (hamilton) [reply src/reducers/notebook-reducer.js]: We will be deprecating `IMPORT_NOTEBOOK`, iirc (@bcolloran has more to say about this I think) - in any case I can remove the `getNotebookInfo` call from it so we don't have this redundancy

Comment (mdboom) [reply src/reducers/notebook-reducer.js]: Ok.  Sure thing.

Comment (bcolloran) [reply src/reducers/notebook-reducer.js]: ya importNotebook and IMPORT_NOTENOOK are kind of legacy -- they're meant to handle e.g. loading from localStorage and the URL trick, which may end up on the chopping block. And importNotebook is only called from within importInitialJsmd; this action+reducer will give us a way to update the clients knowledge about the notebook at any time, not just at load time.
